### ISSUE TITLE
An option to list only direct children

### ISSUE THREAD

**Issue by wischi-chr** [Linbreux/wikmd#100]
I have a pretty large wiki (multiple thousands of files and a ton of folders) but they are structured in a very hierarchical manner, so at every level there are only about a dozen elements. Currently if I list at a very high level (for example the root folder) it iterates all files and takes a very long time to render the page.

It would be great to have the option to only list direct children but not grand-children.

**Comment by Linbreux** [comment]
hi @wischi-chr 

Thanks for sharing!
Yes that would be a great feature instead of listing all the lower level files. I'll try to implement it when I have some spare time :)

**Comment by Linbreux** [comment]
0076c1d083043b12cc79eedd1d0d0215ef0e5383 should fix it :)
