### ISSUE TITLE
Switching theme (light/dark) removes unsaved content

### ISSUE THREAD

**Issue by Jerakin** [Linbreux/wikmd#102]
If you are on `/add_new` and switch to a different theme the content you were writing is discarded.

Preferably the switching theme shouldn't destroy the content, at minimum if you have written any content it should ask if you want to discard your changes or cancel.

**Comment by Linbreux** [comment]
Hi @Jerakin 

I also think a popup would be the easiest way to implement this asap. I'll try to do it when I have some spare time!

**Comment by Jerakin** [comment]
Fixed in https://github.com/Linbreux/wikmd/pull/135
