### ISSUE TITLE
Line edit fields are light in dark mode

### ISSUE THREAD

**Issue by Jerakin** [Linbreux/wikmd#103]
Usually text fields are darker than the background in dark mode themes, which is a lot easier on the eyes.

Current look
![image](https://user-images.githubusercontent.com/5273682/220964474-a1a16f44-141d-46e0-a1e6-96de53eb8ad7.png)

Example of line edits with darker color
![image](https://user-images.githubusercontent.com/5273682/220964718-9fedb671-b206-472c-923c-77caebea1f9f.png)

**Comment by Linbreux** [comment]
Yeah that would definitely be way better :) It should also be easy to implement. Thanks for sharing.

**Comment by Jerakin** [comment]
Fixed in https://github.com/Linbreux/wikmd/pull/131
