### ISSUE TITLE
Improve project structure

### ISSUE THREAD

**Issue by Jerakin** [Linbreux/wikmd#137]
The project have all files dumped into the root. It would be a lot easier if the source files were moved into a sub folder. Either to a flat layout or a src layout.

### flat layout
```
.
├── README.md
├── pyproject.toml
├── setup.py
├── wikmd/
│   ├── plugins/
│   ├── __init__.py
│   ├── cache.py
│   └── wiki.py
└── tests/
    ├──test_basics.py
    └── test_plugins.py
```

### src layout
```
.
├── README.md
├── pyproject.toml
├── setup.py
├── src/
│    └── wikmd/
│            ├── plugins/
│            ├── __init__.py
│            ├── cache.py
│            └── wiki.py
└── tests/
    ├──test_basics.py
    └── test_plugins.py
```

**Comment by Linbreux** [comment]
Hi @Jerakin,

This is a good idea, I was already looking into it, would also be handy to package wikmd. I guess my preference goes to the `src-layout`. If you think the other one would be better, let me know.

**Comment by Jerakin** [comment]
I am also partial to a src layout. Are you looking into this or should I take a stab at it?

**Comment by Linbreux** [comment]
Alright lets do it that way then. I did not look into it yet.
