### ISSUE TITLE
Drawings missing from git

### ISSUE THREAD

**Issue by melvin-suter** [Linbreux/wikmd#150]
Draw.io drawings are not pushed into the git repo, which defeats the purpose of a git-based export a bit. 
Drawings are part of the page and should stay with the rest of the data.

I would suggest moving the drawings folder to the pages folder and hiding it while listing the pages.

**Comment by Linbreux** [comment]
Yes indeed, never thought about it. I'll try to fix it.

Nice to see that the drawio plugin is being used!

**Comment by melvin-suter** [comment]
It is one of the main features I'm setting up wikmd :) awesome project you got going!

**Comment by Linbreux** [comment]
@melvin-suter It is currently merged in the main branch. Let me know if it works as expected now :)
