### ISSUE TITLE
pypandoc error

### ISSUE THREAD

**Issue by DanZ-ix** [Linbreux/wikmd#156]
Hi! 
I am using Windows 10, python 3.11, pip 24.0
I tried to start the application, did everything according to documentation here:
https://linbreux.github.io/wikmd/development.html  
Got a bunch of errors, one of them raised when the application was already running and i tried to create a new file:
OSError: No pandoc was found: either install pandoc and add it
to your PATH or or call pypandoc.download_pandoc(...) or
install pypandoc wheels with included pandoc.

fixed it with installing pypandoc-binary manualy:
pip install pypandoc-binary

I think the documentation about the installation process should be updated)

**Comment by DanZ-ix** [comment]
I can make a PR if its ok)

**Comment by Linbreux** [comment]
@DanZ-ix, yes maybe the python pandoc binaries could be added to the python requirements. Did not know about that, thanks!

The docs do mention the pandoc install though. [https://linbreux.github.io/wikmd/installation/regular_install.html#windows](https://linbreux.github.io/wikmd/installation/regular_install.html#windows)
