### ISSUE TITLE
Dependency on internet access

### ISSUE THREAD

**Issue by pktl** [Linbreux/wikmd#157]
I wanted to try wikimd and deployed using docker compose. However, the NoScript browser plugin blocks a number of scripts that don't originate from the machine where wikimd is deployed on. I'd like to selfhost in my private LAN and loading resources from the internet is kind of against the point of having it selfhosted. Of course internet access is needed to deploy/update, but after that, internet should be optional, imho.

Would you consider removing this dependency on external resources?

**Comment by Linbreux** [comment]
Hi @pktl 

Normally that's why there is a local mode. Did you try that already?

[https://linbreux.github.io/wikmd/environment%20variables.html#local-mode](https://linbreux.github.io/wikmd/environment%20variables.html#local-mode)

**Comment by pktl** [comment]
Should have RTFM ;)
I don't agree with the default, but that's just my personal preference.

Modified `docker-compose.yml` to enable it:
```
environment:
  - LOCAL_MODE=True
```
But it still wants to fetch something from `fonts.gstatic.com`. All other resources are now served by wikimd.

**Comment by Linbreux** [comment]
Alright, thanks for letting us know. I'll look into the fonts when I have some spare time

**Comment by Linbreux** [comment]
@pktl this commit should fix the font issue.

**Comment by pktl** [comment]
Yep, with the latest docker image it works as expected.
