### ISSUE TITLE
[bug] local variable 'repo' referenced before assignment

### ISSUE THREAD

**Issue by artivis** [Linbreux/wikmd#20]
Hi, 
I've hit the following error on [l.147](https://github.com/Linbreux/wikmd/blob/e3c6076fe7c3f51f85504c39f1a6979ceb398f78/wiki.py#L147):

```bash
Traceback (most recent call last):
  File "wiki.py", line 315, in <module>
    gitcom()
  File "wiki.py", line 146, in gitcom
    repo.git.add("--all")
UnboundLocalError: local variable 'repo' referenced before assignment
```

**Comment by Linbreux** [comment]
Hi did you use 

```
pip install -r requirements.txt
```
Could you give a little more info? Did you use virtualenv or do you have git installed?

**Comment by artivis** [comment]
Hey, thanks for the prompt reply.

I'm messing around building my own Docker and my particular issue is a permission issue: `git.Repo.init(WIKI_DATA)` gets a permission denied. That's on me and I'm fixing it.

However, if for any reason the `try` block preceding l.147 fails, the `repo` variable is indeed referenced before being assigned. You may want to enclose it in its own `try` block or what not?

**Comment by Linbreux** [comment]
I looked into the code, and you are right that there is a bug. #21 should fix this. Though, this means that you still have a problem using the versioning system. If this did not fix it, feel free to reply!

**Comment by Linbreux** [comment]
> I'm messing around building my own Docker and my particular issue is a permission issue: `git.Repo.init(WIKI_DATA)` gets a permission denied. That's on me and I'm fixing it.

Did you use the [Dockerfile](https://github.com/Linbreux/wikmd/blob/main/Dockerfile)? I'm not that experienced with Docker, so there might be an issue on my part.

**Comment by artivis** [comment]
Nop I'm creating my own image (hence my own Dockerfile).
I've tried again and the issue seems to be fixed :+1:
