### ISSUE TITLE
Docker file

### ISSUE THREAD

**Issue by artivis** [Linbreux/wikmd#23]
Hi @Linbreux,

I've created a Docker file for `wikmd` that is loosely inspired by those of the [`linuxserver`](https://www.linuxserver.io/) community and I've successfully tested it on amd64 and arm (raspberry pi + raspbian). You can [find them on my fork](https://github.com/artivis/wikmd/tree/docker/docker).

I don't really plan on actively maintaining it as I won't fully transition to `wikmd` just yet. Are you interested in a PR? Maybe that could even support a `wikmd` application for support by the `linuxserver` community who knows.

**Comment by Linbreux** [comment]
Hi @artivis 

Really appreciate the work you put into Wikmd. A PR would be great! Also, nice documentation! 

> I don't really plan on actively maintaining it as I won't fully transition to wikmd just yet. 

That's no problem. Do you got any features, that you would like to see implemented in the wiki?

**Comment by artivis** [comment]
Hi,

Would you prefer a PR against this repo or host the docker file in a separate one? The way it is set up now allows for the later since the Docker file script actually pull the code directly from the `wikmd` repo's master branch.

Regarding features, let me start by saying that I like that `wikmd` is file-based. It allows me to keep my existing folder-based organization and not being locked in any vendor system or database. Plus it is a self-hostable web-based app, super great! 
But since you are asking, let me draft a wish-list here:

- read-only access
- multi-user (somewhat related to the above bullet)
- per-file tagging - for search/filtering based on tags; e.g. looking for '`raspberry-pi`'-related files across sub-directories.

In case this is your actual underlying question, I'm not switching to `wikdm` just yet simply because I'm to used to my current flow. At the moment I'm using vs-code with a whole bunch of markdown plugins (auto-complete, syntax check, spell check, live preview etc). Editor aside, using `wikmd` would alleviate a few pain points tho.

**Comment by Linbreux** [comment]
Hi @artivis 

For now you can create a PR in this repo. I can fix this later on. 

In terms of features I'm still not sure if I would integrate user auth since I'm not sure how I want it to work.

The tagging is a great idea, i'll try to implement it in a later release!

Appreciate the honest feedback, thanks!
