### ISSUE TITLE
Commit bug due to (my) refactoring

### ISSUE THREAD

**Issue by Mik3Rizzo** [Linbreux/wikmd#26]
[This line](https://github.com/Linbreux/wikmd/blob/76637629a0b0c5b5788b0d6d531cb3602a2ae782/wiki.py#L170):
```python 
repo.git.git_commit('-m', commit)
```
Should be:
```python 
repo.git.commit('-m', commit)
```
Otherwise commits don't work.

I was developing git push to remote repos when I discovered this annoying bug. I may have introduced it due to the automatic refactoring. Sometimes it could be a pain: my bad, sorry!

**PS.** I've already implemented configuration through an handy `.yaml` file ;-) Tomorrow I'll do a PR (with the above bug fixed as well).

**Comment by Linbreux** [comment]
Hi,
Thanks for sharing I'll have a look at it!
