### ISSUE TITLE
git checkout error for initialized repo

### ISSUE THREAD

**Issue by Mik3Rizzo** [Linbreux/wikmd#27]
When starting again the wiki, the initialization of the repo fails and commits will not be added.

Here's the log:
```
cmdline: git checkout -b master
stderr: 'fatal: a branch named 'master' already exists'
```

I may have fixed it dropping the `-b` parameter if the repo has already been initialized.

**Comment by Linbreux** [comment]
> I may have fixed it dropping the -b parameter if the repo has already been initialized.

Yes but like you said, this can only be done once the repo is already initialized.

**Comment by Mik3Rizzo** [comment]
> this can only be done once the repo is already initialized.

This is true, but the `-b` switch creates a new branch. It is fine if the repo is initialized and "empty" (so it is brand new), but if the repo is an existing (and not empty) one the command gives me the reported error.

I also noticed that [this initialization block](https://github.com/Linbreux/wikmd/blob/76637629a0b0c5b5788b0d6d531cb3602a2ae782/wiki.py#L156-L164) is executed every time there is a new commit. I think it should be executed once at the beginning. In this way - I have not figured yet why - the console logger `app.logger` starts to work and shows messages. Leaving the initialization block before every commit makes the logger not to work in my case. 

Have you got any idea why?

**Comment by Linbreux** [comment]
I have a look at it. I currently got an error on init.
```[2022-03-14 19:58:39,236] ERROR in wiki: Error during git initialization: Cmd('git') failed due to: exit code(1)
  cmdline: git checkout master
  stderr: 'error: pathspec 'master' did not match any file(s) known to git'
```
