### ISSUE TITLE
Hello, can you provide a demo? Thank you

### ISSUE THREAD

**Issue by y377** [Linbreux/wikmd#4]
Thank you for your open source, can you provide a demo for other users to view? At the same time I am also considering building a wiki program (wiki.xin)

**Comment by Linbreux** [comment]
I did not yet look for a good webhost for this. Also, I have not implemented user auth, what would be kinda required for this. If you got any recommendations let me know ;)

If you would like to contribute to wikmd be my guest!

**Comment by y377** [comment]
ok，i try it



---Original---
From: ***@***.***&gt;
Date: Thu, May 13, 2021 03:07 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Linbreux/wikmd] Hello, can you provide a demo? Thank you (#4)




 
I&nbsp;did&nbsp;not&nbsp;yet&nbsp;look&nbsp;for&nbsp;a&nbsp;good&nbsp;webhost&nbsp;for&nbsp;this.&nbsp;Also, I have not implemented user auth,&nbsp;what&nbsp;would&nbsp;be&nbsp;kinda&nbsp;required&nbsp;for&nbsp;this.&nbsp;If&nbsp;you&nbsp;got&nbsp;any&nbsp;recommendations let&nbsp;me&nbsp;know&nbsp;;)
 
If you would like to contribute to wikmd be my guest!
