### ISSUE TITLE
wikmd on Windows: Bug when converting markdown in internal editor

### ISSUE THREAD

**Issue by domasofan** [Linbreux/wikmd#40]
Hi,

It seems there is an issue when converting written markdown in the internal editor.
Tested on a German/European Windows version.
It seems it saved the md file as ANSI/ISO-8859-1 instead of UTF-8.
So Pandoc seems to complain about that:

INFO:wiki:Saving >>> 'Test' ...
INFO:wiki:Converting to HTML with pandoc >>> 'wiki\Test.md' ...
INFO:wiki:New git commit >>> Add page 'Test' on 2022-04-23 01:48:26.530440
INFO:wiki:Pandoc died with exitcode "92" during conversion: b'UTF-8 decoding error in wiki\\Test.md at byte offset 31 (f6).\r\nThe input must be a UTF-8 encoded text.\r\n'

**Comment by Linbreux** [comment]
I'll try to solve this at the end of the week. The encoding does sometimes a little weird... can you give a little more detail? Do you use docker, a virtualenv or native?

**Comment by Mik3Rizzo** [comment]
@domasofan Please, try my [fork](https://github.com/Mik3rizzo/wikmd.git) and tell me if it fixes your problem.
