### ISSUE TITLE
Publish a new Docker image

### ISSUE THREAD

**Issue by kura** [Linbreux/wikmd#41]
Hey. Any chance you can publish newer Docker images? The latest image doesn't contain any of the recently added functionality.

**Comment by Linbreux** [comment]
hi @kura,

Sorry for the delay, I've been busy. I tried to build a new image, but got some problems implementing the latest code release. I'll try to do it this week.

**Comment by kura** [comment]
@Linbreux no worries. When I tested this locally I had to make a few changes to install the newest requirements, as well as add some now required environment variables to get it all working. And then I promptly forgot I did it and redeployed the container, wiping out my changes. :D

No rush, honestly this was more of a prompt that the image on Docker Hub was falling behind the code on GitHub 'cos I figured no automated image update was being made than any desperate need for the newest version (excluding maybe the favicon which would be a super nice-to-have.)

**Comment by Linbreux** [comment]
@kura I think everything is working for know. Let me know if it isn't :D

**Comment by kura** [comment]
@Linbreux I just redeployed, pulling the latest image and it's working as expected.

In the future, when you publish a new release on GH is it going to auto-push a release to Docker Hub too?

**Comment by Linbreux** [comment]
For now, I'll do it manualy. I'm looking into automating this.

**Comment by kura** [comment]
Ok, sounds good.

**Comment by Oliver-Hanikel** [comment]
Automated builds would be greatly appreciated. Docker Hub has a way to auto build on [specific tags](https://docs.docker.com/docker-hub/builds/#tag-and-branch-builds).

**Comment by Linbreux** [comment]
Normaly the releases and main (edge) branch will be published automaticly to dockerhub thanks to @artivis
