### ISSUE TITLE
[enhancement] add token support to replace ssh connect would be better

### ISSUE THREAD

**Issue by Eloco** [Linbreux/wikmd#43]
just a advice
using `${{env.repo}}` and `${{env.token}}` to connect the github repo

btw : add a basic auth or pass for the edit part would be better

**Comment by Linbreux** [comment]
Thanks for the feedback

> using ${{env.repo}} and ${{env.token}} to connect the github repo

I'll at it to the todo. Good idea!

> btw : add a basic auth or pass for the edit part would be better

I don't know if I would like to go that route. This would at a lot of complexity to the "simple wiki". Especially when using multiple users (permissions etc...). If you have a clean way in mind, feel free to post it!

**Comment by Eloco** [comment]
for the first advice, thanks for your acceptance.

>I don't know if I would like to go that route. This would at a lot of complexity to the "simple wiki". Especially when using multiple users (permissions etc...). If you have a clean way in mind, feel free to post it!

yes, simple is the key for self-hosted. 
but if u post the wiki online, at least the editor part have a simple encryption, in case every one can modify your repo data.

**Comment by Linbreux** [comment]
hi @Eloco 

I added a basic password protection in #48, let me know if it fits your needs.
