### ISSUE TITLE
Stop using JS from CDNs and host locally instead

### ISSUE THREAD

**Issue by kura** [Linbreux/wikmd#50]
I don't really like that an app I am hosting myself on my network is requesting JS files from an external CDN, even with SRI. Can those JS files just be included in the repo and hosted locally instead?

**Comment by Linbreux** [comment]
I'm trying to just link to the files as much as possible instead of including them. Maybe there is a way to download them just at installing wikmd, but I have not looked into that yet. Maybe a install script would do the trick.

**Comment by kura** [comment]
Something like that would be good, yeah. Or a config option that switches into a self-contained mode, when the process starts it can see that option is enabled, check the local filesystem for a local copy of the external libraries and if they don't exist, download them, switching to local filesystem mode in the templates too.

**Comment by Linbreux** [comment]
Hi @kura, 
@Oliver-Hanikel added the functionality you suggested. I'll close this issue for now.

**Comment by kura** [comment]
Perfect, thanks both!
