### ISSUE TITLE
Temp created as root

### ISSUE THREAD

**Issue by l-maciej** [Linbreux/wikmd#52]
Hi 

I'm using docker-compose to start service : 

```docker
version: "2.1"
services:
  wikmd:
    image: linbreux/wikmd:latest
    container_name: wikmd
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Warsaw
      - WIKI_DIRECTORY=/pages
      - HOMEPAGE=homepage.md
      - HOMEPAGE_TITLE=Homepage
      - SYNCH_WITH_REMOTE=1
      - REMOTE_URL="XXXXX"
      - GIT_USER=wikmdSYnc
      - GIT_EMAIL=wikmd@null.lan
      - MAIN_BRANCH_NAME=workingcopy
    volumes:
    - pages:/pages
    ports:
      - 5000:5000
    restart: unless-stopped
volumes:
  pages:
```
After docker-compose up two errors are showing up: 

![image](https://user-images.githubusercontent.com/95386532/178093934-7d14445a-9015-45ad-b041-56daf700503d.png)

/wiki is still used as default or just wiki tries to empty out folder.  Application is trying to move data from  /wiki it to non-existing temp folder not permitted to user with GID 1001 (non-root user on host machine) -> it causes loads of logs and machine load

/pages is created and correct permission are added

**Comment by Linbreux** [comment]
Alright thanks for noticing and the detailed instructions. I think the is because the wiki folder is hardcoded [here](https://github.com/Linbreux/wikmd/blob/main/docker/root/etc/cont-init.d/30-config#L10-L26) and this should be an environment variable.

I'll fix it asap. Does it work when you do not specify the directory?

**Comment by l-maciej** [comment]
```docker
version: "2.1"
services:
  wikmd:
    image: linbreux/wikmd:latest
    container_name: wikmd
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Warsaw
      - WIKI_DIRECTORY=/pages
      - HOMEPAGE=homepage.md
      - HOMEPAGE_TITLE=Homepage
      - SYNCH_WITH_REMOTE=1
      - REMOTE_URL="XXXXX"
      - GIT_USER=wikmdSYnc
      - GIT_EMAIL=wikmd@null.lan
      - MAIN_BRANCH_NAME=workingcopy
    volumes:
    - pages:/pages
    ports:
      - 5000:5000
    restart: unless-stopped
volumes:
  pages:
```
Causes same issue with moving data to temp folder 

![image](https://user-images.githubusercontent.com/95386532/178099017-789a3c81-2139-4142-b207-5c3624e7365c.png)

Maybe  different init method when using sync with remote is enabled - just remove all examples since data will be pulled from git anyway

**Comment by artivis** [comment]
Hi @l-maciej,

Why don't you simply mount your volume under `/wiki` (and remove `WIKI_DIRECTORY`)?

```yaml
...
volumes:
    - pages:/wiki
...
```

As for the permission issue in `/tmp`, a possible fix could be to change the permission, e.g. changing [this line](https://github.com/Linbreux/wikmd/blob/main/docker/root/etc/cont-init.d/30-config#L7) as

```bash
  chown abc:abc /var/log/wikmd.log /tmp
```

Without having tested it I'm not sure if it would cause other issues tho.

**Comment by l-maciej** [comment]
Hi @artivis  
Mounted  data folder to /wiki and application stared without issues and excessive logging.

But in turn I've noticed strange behavior with knowledge graph - it needs access to /wiki/.bash_history  to work.
But mentioned file is root owned - I think that something goes wrong [here](https://github.com/Linbreux/wikmd/blob/d3822face22874ac2287b3a52f4bd1faaf209a0a/knowledge_graph.py#L21)
Maybe small change in regex will exclude dotted files ? 


![2022-07-22 12_35_21-PermissionError_  Errno 13  Permission denied_ '_wiki_ bash_history' __ Werkzeug](https://user-images.githubusercontent.com/95386532/180422592-faee66ca-2655-4737-98b6-24cd3055f172.png)

![2022-07-22 12_35_53-Jenkins Agent](https://user-images.githubusercontent.com/95386532/180422249-80f9ad00-165c-42d8-8905-55ccb6a26f8d.png)
