### ISSUE TITLE
Toggling darkmode results in an error

### ISSUE THREAD

**Issue by dkgof** [Linbreux/wikmd#76]
When pressing the toggle darkmode icon in the upper left, i get the following error:

`FileNotFoundError
FileNotFoundError: [Errno 2] No such file or directory: '/wiki/toggle-darktheme/None.md'`

If i afterwards go back to the main page, or any other page, the theme has actually toggled, so its just the redirect that is not working.

I am running it from docker.

**Comment by Linbreux** [comment]
Hi @dkgof 

Thanks for letting me know, I'll check it!

**Comment by Linbreux** [comment]
@dkgof what page were you on when you switched themes?

**Comment by dkgof** [comment]
It seems to happen no matter what page i am on. My homepage, or any other page.

**Comment by Linbreux** [comment]
Hi @dkgof,
We use [`Referer`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer) to return to the page where you pressed the toggle switch. If you could give a little more detailed information. What version are you running? Does the page still exist?

**Comment by dkgof** [comment]
I am running it behind a reverse nginx proxy, maybee something needs to be setup that i forgot to support this?

Not entirely sure how to see the version, but i installed it from your docker-compose example a few hours ago. So the latest version?

When looking at the network traffic in chrome dev tools, i dont see the Referer header, maybee that is the problem?

**Comment by dkgof** [comment]
Just tested without the reverse proxy, directly from the IP, then it works. So i guess the proxy is doing something.

**Comment by dkgof** [comment]
Apparently, digging a bit more into it, nginx does not proxy `Referer`, so as a temporary fix, i added `Referer "/"`, so when i switch darkmode on/off, it sends me back to the frontpage, instead of the error. I guess that works well enough for me.

**Comment by Oliver-Hanikel** [comment]
Some people also disable the Referer Header for privacy reasons in their Browser. We could instead put the current URL as a redirect in the link. Like it is done for the login.
