### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by adamwojt** [Linbreux/wikmd#78]
I am really missing sticky NavBar on the left for this library. i think it might be bit different request than https://github.com/Linbreux/wikmd/issues/51
Virtually all docs have this.

![image](https://user-images.githubusercontent.com/45100954/191324214-ea8d23fe-9300-4d42-8efc-b8a183bf9794.png)
![image](https://user-images.githubusercontent.com/45100954/191324275-d675168f-6556-435b-b415-34062a995c3b.png)
![image](https://user-images.githubusercontent.com/45100954/191324322-5cfde495-5a2f-44ae-a396-d6859be8d2c0.png)

**Comment by Linbreux** [comment]
Hi @adamwojt,
What kind of navbar do you mean? A table of contents of the current page? We are currently working of a `[[toc]]` macro, there are also plans to create a sidebar. https://github.com/Linbreux/wikmd/discussions/70#discussioncomment-3614896

**Comment by adamwojt** [comment]
@Linbreux The sidebar on the left. I guess it's a dupe then. I thought that the macro issue is bit different than that.

**Comment by Linbreux** [comment]
@adamwojt 
The sidebar is on the TODO list ;) We just need to find a good way to integrate it.
I'll notify you when we are there!

**Comment by skjerns** [comment]
Is this still on the "not planned" list?

I think a sidebar would be really useful feature!

**Comment by Linbreux** [comment]
Hi @skjerns,
I am currently working on this. For now I'm thinking of something like the image bellow:
![image](https://user-images.githubusercontent.com/29354411/216122613-b7ffcf47-75de-4751-b35d-a93516cd6fd6.png)

On the left a customizable sidebar, maybe a yaml or something.
On the right a table of contents.

Suggestions or PR's :)  are always welcome.

**Comment by Jerakin** [comment]
I have started on this. How does something like this look?

 I think that having practically having the whole folder structure would be the best. Then on the right side we could add the table of content like in Linbreux example above.


https://github.com/Linbreux/wikmd/assets/5273682/a5e1c352-a5c4-4eb7-b874-8c8dfdd7707d

**Comment by Linbreux** [comment]
@Jerakin This looks clean! Keep in mind that a bunch of people have a lot of files in there root folder (50+).

**Comment by Jerakin** [comment]
Yeah, if there is a lot of files there will be a scrollbar
![image](https://github.com/Linbreux/wikmd/assets/5273682/d4628a0a-ba88-4a0c-89b1-6369d6a19d6e)

**Comment by Jerakin** [comment]
I was thinking that it would be really cool that if you had a structure like this 

```
wiki/
├─ gummi/
│  ├─ cupcake.md
│  ├─ fruitcake.md
├─ gummi.md
├─ how to use the wiki.md
```

The the `gummi.md` file wouldn't show up in the list but rather it would be rendered if you pressed the `gummi` folder. This would require a bit of change though as currently you can press anywhere on the folder name to expand it, if we added that functionality you would need to press on the arrow only to expand it.
