### ISSUE TITLE
raspberry with docker - standard_init_linux.go:219: exec user process caused: exec format error

### ISSUE THREAD

**Issue by Export33** [Linbreux/wikmd#81]
Hi,

when using `linbreux/wikmd:latest` on a raspberry with docker i get the follwing error at startup:
`standard_init_linux.go:219: exec user process caused: exec format error`
As far as i read the architecture is propably the issue.
What is the correct image for `ARM`?

**Comment by Oliver-Hanikel** [comment]
Currently there is no prebuilt image for arm32. You have to build it yourself.

**Comment by Export33** [comment]
Ok, thanks. I will try that.
